# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Ruff linting and formatting
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    # Run the linter.
      - id: ruff-check
        files: ^(hts_synth|tests)/.*\.py$
        always_run: true
    # Run the formatter.
    #   - id: ruff-format
    #     files: ^(hts_synth|tests)/.*\.py$
    #     always_run: true

# BasedPyright static type checking
- repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
  rev: v1.13.0
  hooks:
    - id: basedpyright
