name: Lint

on:
  - push
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt -r requirements.txt

      - name: Run linting
        uses: astral-sh/ruff-action@v3
